name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code from repository
      - uses: actions/checkout@v4

      # Cài đặt Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'  # Đảm bảo bạn chọn phiên bản Flutter bạn cần

      # Chạy lệnh build web
      - run: flutter build web

      # Deploy lên Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_3030F }}
          channelId: live
          projectId: portfolio-3030f
